### ISSUE TITLE
Regarding the Source Data

### ISSUE THREAD

**Issue by ZhPL1** [Zhuofeng-Li/TEG-Benchmark#2]
Hi Zhuofeng,

Thanks for your efforts on this project.

I wonder if the '.npy' files for most datasets are missing in your [Huggingface TEG-Benchmark]. There seems to be only the 'raw' folders.

Thanks again for your attention.

**Comment by Zhuofeng-Li** [comment]
Hi, we're gradually uploading our embeddings because they are large. I will let you know once we finished.

**Comment by Zhuofeng-Li** [comment]
We have provided embedding file from bert and large bert. Please  check https://huggingface.co/datasets/ZhuofengLi/TEG-Datasets
