### ISSUE TITLE
About Node Embedding of GoodReads

### ISSUE THREAD

**Issue by LvAoAo** [Zhuofeng-Li/TEG-Benchmark#3]
Hello, Thank you for your great job.

When I tried to replicate the code, I found that the node embedding in the code is initialized from scratch instead of loading from PLM embedding on text attributes. However, the genres of books and the descriptions are abandoned. I don't know how you processed them, or did you just take them as node text attributes directly? So is the code updated? 
Would you upload the latest code? Thank you!

```
self.user_emb = torch.nn.Embedding(data["user"].num_nodes, hidden_channels)
self.book_emb = torch.nn.Embedding(data["book"].num_nodes, hidden_channels)
self.genre_emb = torch.nn.Embedding(data["genre"].num_nodes, hidden_channels)
```

**Comment by Zhuofeng-Li** [comment]
Hi, we are cleaning codes now. We will update the codes before 10.30.

**Comment by Zhuofeng-Li** [comment]
We have updated GNN codes in the `GNN` folder. Please check.
